namespace DisneyCharacters.Model
{
    /** 
     * Autogenerated from https://app.quicktype.io/
     */
    public partial class CharacterListDto
    {
        public Info Info { get; set; }
        public List<CharacterDataDto> Data { get; set; }
    }

    public partial class CharacterDataDto
    {
        public long Id { get; set; }
        public string[] Films { get; set; }
        public string[] ShortFilms { get; set; }
        public object[] TvShows { get; set; }
        public string[] VideoGames { get; set; }
        public string[] ParkAttractions { get; set; }
        public object[] Allies { get; set; }
        public object[] Enemies { get; set; }
        public Uri SourceUrl { get; set; }
        public string Name { get; set; }
        public Uri ImageUrl { get; set; }
        public DateTimeOffset CreatedAt { get; set; }
        public DateTimeOffset UpdatedAt { get; set; }
        public Uri Url { get; set; }
        public long V { get; set; }
    }

    public partial class Info
    {
        public long Count { get; set; }
        public long TotalPages { get; set; }
        public object PreviousPage { get; set; }
        public object NextPage { get; set; }
    }
}
